spring.application.name=SmartExpenseTracker
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=railway
spring.datasource.password=FgDfqpwegeyLMBxRBFICDuWbRzcEUBUu

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.thymeleaf.cache=false
