spring.application.name=SmartExpenseTracker

spring.datasource.url=jdbc:mysql://51.20.81.190:3306/expense_db
spring.datasource.username=root
spring.datasource.password=root123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.thymeleaf.cache=false
